# Generated by Django 3.1.4 on 2020-12-29 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(unique=True)),
                ('short_url', models.URLField(unique=True)),
                ('clicks', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
