# Generated by Django 3.1.4 on 2020-12-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='clicks',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
