# Generated by Django 3.1.4 on 2020-12-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_url_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
